### ISSUE TITLE
Error when adding actions to event in 1.2.1 (F-Droid) running on Android 11 (Samsung A50)

### ISSUE THREAD

**Issue by empjustine** [Nain57/Smart-AutoClicker#62]
When attempting to add another "action" to an "Event", the "actions" area will get in a bad state where the next touch will result in a crash.

Stack trace of the bad state captured by taco.scoop in Android 11:

```
FATAL EXCEPTION: main
Process: com.buzbuz.smartautoclicker, PID: 27861
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionf{e8b8bcd position=3 id=-1, oldPos=2, pLpos:2 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{803ade0 VFEDH.... ......ID 21,105-835,432 #7f0800f1 app:id/list_actions}, adapter:p1.g@9823216, layout:androidx.recyclerview.widget.LinearLayoutManager@ab63797, context:android.view.ContextThemeWrapper@a4fdd84
	at androidx.recyclerview.widget.RecyclerView$t.j(:33)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(:3)
	at androidx.recyclerview.widget.LinearLayoutManager.f1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.S0(:2)
	at androidx.recyclerview.widget.LinearLayoutManager.l0(:17)
	at androidx.recyclerview.widget.RecyclerView.r(:19)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(:2)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.cardview.widget.CardView.onMeasure(Unknown Source:0)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27131)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(Unknown Source:38)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.core.widget.NestedScrollView.onMeasure(Unknown Source:0)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27131)
	at androidx.appcompat.widget.AlertDialogLayout.onMeasure(:1)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:154)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1173)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4200)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2922)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3217)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2631)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9984)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:744)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by Nain57** [comment]
[Smart-AutoClicker 1.2.2](https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.2.2) is now available. It should fix this issue.
The update should be available soon on F-Droid.
